%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
pic_dir: /home/xxz/data
# camera intrinsics
# fr1
blockSize: 12
disparity: -25
zero_disparity: -6
sobelLimit: 860
sadThreshold: 54
check_horizontal_invariance: true
horizontalInvarianceMultiplier: 1

# fr2
#camera.fx: 520.9
#camera.fy: 521.0
#camera.cx: 325.1
#camera.cy: 249.7
matQ[0][3]: -599.4130706787109
matQ[1][3]: -356.5859909057617
matQ[2][3]: 726.7854265077029
matQ[3][2]: -0.008382265446029592
# VO Parameters
OCTREE_RESOLUTION: 128.0f

INVARIANCE_CHECK_VERT_OFFSET_MIN: -8
INVARIANCE_CHECK_VERT_OFFSET_MAX: 8
INVARIANCE_CHECK_VERT_OFFSET_INCREMENT: 2
INVARIANCE_CHECK_HORZ_OFFSET_MIN: -3
INVARIANCE_CHECK_HORZ_OFFSET_MAX: 3
